version: "3"

volumes:
  minio:
  postgres:
  redis:

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio:/data
    command: server /data
    env_file:
      - .env

  web:
    tty: true
    stdin_open: true
    depends_on:
      - minio
      - postgres
      - redis
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres@postgres:5432
      MINIO_ENDPOINT: http://minio:9000
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PORT: 3035

  webpacker:
    depends_on:
      - web
    build: .
    command: bin/webpack-dev-server
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 3035:3035
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PORT: 3035
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    command: sidekiq
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres@postgres:5432
